### ISSUE TITLE
CPUTIN and SYSTIN show negative temperatures.

### ISSUE THREAD

**Issue by phdzor** [lm-sensors/lm-sensors#246]
Hello, when i log to my Arch Linux sensors show normal temperatures for cpu and system but after some time when i chceck temperatures again sensors show negative temperatures for cpu and system. Is there any way to fix that ? Thanks.

i have the latest sensors version 3.6.0 with libsensors version 3.6.0, my MB is ASUS P8Z77-V PRO and CPU is Intel i5-3570k.

![Image of Temps](https://user-images.githubusercontent.com/51232573/85197705-076b1500-b2e3-11ea-91b6-7e33834c9218.png)

**Comment by olysonek** [comment]
Hi. If the values float, I would guess that the inputs simply aren't connected to anything on the board, so there would be nothing we can do.

Almost certainly, the problem is not related to lm_sensors, as `sensors` just reads values from sysfs exported by the kernel. But you can make `sensors` ignore the inputs by putting an `ignore` statement to its config file.
